### ISSUE TITLE
一些issues

### ISSUE THREAD

**Issue by GoingMyWay** [windworst/openshit#1]
你好，你的`openshit`工具安装`OpenStack`很方便，很荣幸用你的工具在Ubuntu 14.04单机上安装`OpenStack`，但是这里也有一些问题，请你有时间解决一下
- **AMQP server on 127.0.0.1:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.**

给你看一下日志

```
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db Traceback (most recent call last):
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/servicegroup/drivers/db.py", line 99, in _report_state
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     service.service_ref, state_catalog)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/conductor/api.py", line 180, in service_update
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return self._manager.service_update(context, service, values)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/utils.py", line 973, in wrapper
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return func(*args, **kwargs)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/oslo/messaging/rpc/server.py", line 139, in inner
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return func(*args, **kwargs)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 320, in service_update
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     svc = self.db.service_update(context, service['id'], values)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/db/api.py", line 150, in service_update
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return IMPL.service_update(context, service_id, values)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 125, in wrapper
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return f(*args, **kwargs)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 181, in wrapped
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return f(*args, **kwargs)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 524, in service_update
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     with_compute_node=False, session=session)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 424, in _service_get
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     result = query.first()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2341, in first
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     ret = list(self[0:1])
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2208, in __getitem__
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return list(res)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return self._execute_and_instances(context)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2425, in _execute_and_instances
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     close_with_result=True)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2416, in _connection_from_session
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     **kw)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 854, in connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     close_with_result=close_with_result)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return self.transaction._connection_for_bind(engine)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 329, in _connection_for_bind
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     transaction = conn.begin()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 420, in begin
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     self.__transaction = RootTransaction(self)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1357, in __init__
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     self.connection._begin_impl(self)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 490, in _begin_impl
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     self.dispatch.begin(self)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 260, in __call__
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     fn(*args, **kw)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/oslo/db/sqlalchemy/session.py", line 331, in _begin_ping_listener
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     connection.scalar(select([1]))
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 659, in scalar
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return self.execute(object, *multiparams, **params).scalar()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return meth(self, multiparams, params)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return connection._execute_clauseelement(self, multiparams, params)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     compiled_sql, distilled_params
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 893, in _execute_context
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     None, None)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1169, in _handle_dbapi_exception
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     dbapi_conn_wrapper = self.connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 236, in connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return self._revalidate_connection()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 244, in _revalidate_connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     self.__connection = self.engine.raw_connection()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1848, in raw_connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return self.pool.unique_connection()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 280, in unique_connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return _ConnectionFairy._checkout(self)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 641, in _checkout
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     fairy = _ConnectionRecord.checkout(pool)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 442, in checkout
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     dbapi_connection = rec.get_connection()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 505, in get_connection
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     self.connection = self.__connect()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 537, in __connect
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     connection = self.__pool._creator()
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 96, in connect
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     connection_invalidated=invalidated
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     reraise(type(exception), exception, tb=exc_tb)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 90, in connect
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return dialect.connect(*cargs, **cparams)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 377, in connect
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return self.dbapi.connect(*cargs, **cparams)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     return Connection(*args, **kwargs)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db     super(Connection, self).__init__(*args, **kwargs2)
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db OperationalError: (OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (111)") None None
2016-06-19 17:07:48.351 4209 TRACE nova.servicegroup.drivers.db
2016-06-19 17:07:48.536 4209 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: [Errno 104] Connection reset by peer
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 670, in ensure
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 765, in _consume
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=poll_timeout)
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/kombu/connection.py", line 279, in drain_events
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 90, in drain_events
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/connection.py", line 320, in drain_events
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     return amqp_method(channel, args)
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/connection.py", line 523, in _close
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     self._x_close_ok()
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/connection.py", line 551, in _x_close_ok
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     self._send_method((10, 51))
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 56, in _send_method
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     self.channel_id, method_sig, args, content,
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/method_framing.py", line 221, in write_method
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     write_frame(1, channel, payload)
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/transport.py", line 177, in write_frame
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     frame_type, channel, size, payload, 0xce,
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/eventlet/greenio.py", line 308, in sendall
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     tail = self.send(data, flags)
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/eventlet/greenio.py", line 293, in send
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit     total_sent += fd.send(data[total_sent:], flags)
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit error: [Errno 104] Connection reset by peer
2016-06-19 17:07:48.536 4209 TRACE oslo.messaging._drivers.impl_rabbit
2016-06-19 17:07:48.538 4209 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2016-06-19 17:07:49.539 4209 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 127.0.0.1:5672
2016-06-19 17:07:49.555 4209 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 127.0.0.1:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.
2016-06-19 17:07:50.563 4209 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2016-06-19 17:07:51.258 4209 INFO nova.openstack.common.service [-] Caught SIGTERM, exiting
2016-06-19 17:08:15.444 5615 AUDIT nova.service [-] Starting scheduler node (version 2014.2.4)
2016-06-19 17:08:15.997 5615 INFO oslo.messaging._drivers.impl_rabbit [req-37837a1e-cecc-473b-ade0-69eb4f646525 ] Connecting to AMQP server on 127.0.0.1:5672
2016-06-19 17:08:16.009 5615 INFO oslo.messaging._drivers.impl_rabbit [req-37837a1e-cecc-473b-ade0-69eb4f646525 ] Connected to AMQP server on 127.0.0.1:5672
```

我不清楚rabbitmq，请问这个错误该怎么处理？
- **AMQP server localhost:5672 closed the connection. Check login credentials: Socket closed**

请问这个错误该怎么处理？
- **mysql bind-address**的问题

需要在`/etc/mysql/my.cnf`把`bind-address = 0.0.0.0`改为`bind-address = 127.0.0.1`,同时在`service`的目录下的`mysql`脚本中也应该把

```
edit_mysql_config()
{
  echo "[mysqld]"
  echo "bind-address = 0.0.0.0"
  echo "default-storage-engine = InnoDB"
  echo "collation-server = utf8_general_ci"
  echo "init-connect = 'SET NAMES utf8'"
  echo "character-set-server = utf8"
}
```

中的`echo "bind-address = 0.0.0.0"`改为`echo "bind-address = 127.0.0.1"`.
- **--force-yes**的问题

在`openshit.sh`中，需要在安装软件的代码中添加`--force-yes`，让Ubuntu可以安装一些不信任的软件。我的软件源是香港中文大学的。

我觉得这里的错误很多都是软件的配置问题，可能需要再你的工具的配置文件里面修改一下。

**Comment by windworst** [comment]
你好 你的问题
**AMQP server on 127.0.0.1:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.**
可能是由于rabbitmq未开启/部署成功, 或者是防火墙规则导致的服务端口无法访问, 请检查服务是否开启,配置是否正确或者服务端口是否允许连接.
**mysql绑定ip**
我当初考虑到可以用脚本部署多台主机的OpenStack, 默认使用的是0.0.0.0, 如果你考虑到安全方面问题, 仅限本机连接mysql 可以自行设置为127.0.0.1或者unix-socket.
**--force-yes** 
是apt软件管理器的一个安全机制, 如果想要安装不信任的软件, 可以自行设置环境变量
export force=yes

**Comment by Ottoqin** [comment]
你好！我最近也在用openshit安装openstack,安装后Nova-conductor日志一直在报错，请问这个是什么问题，谢谢！
2016-07-05 19:29:59.772 111142 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 192.168.176.131:5672
2016-07-05 19:29:59.807 111142 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 192.168.176.131:5672
2016-07-05 19:29:59.813 111142 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to publish message to topic 'reply_11a932d102d048c2ab3fd74ff67c0b33': Exchange.declare: (404) NOT_FOUND - no exchange 'reply_11a932d102d048c2ab3fd74ff67c0b33' in vhost '/'
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 670, in ensure
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 785, in _publish
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     publisher = cls(self.conf, self.channel, topic=topic, **kwargs)
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 375, in __init__
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     type='direct', **options)
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 339, in __init__
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     self.reconnect(channel)
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 347, in reconnect
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     routing_key=self.routing_key)
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 82, in __init__
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     self.revive(self._channel)
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 216, in revive
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     self.declare()
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 102, in declare
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     self.exchange.declare()
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/kombu/entity.py", line 166, in declare
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     nowait=nowait, passive=passive,
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/channel.py", line 620, in exchange_declare
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     (40, 11),  # Channel.exchange_declare_ok
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 69, in wait
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     return self.dispatch_method(method_sig, args, content)
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 87, in dispatch_method
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     return amqp_method(self, args)
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/dist-packages/amqp/channel.py", line 241, in _close
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit     reply_code, reply_text, (class_id, method_id), ChannelError,
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit NotFound: Exchange.declare: (404) NOT_FOUND - no exchange 'reply_11a932d102d048c2ab3fd74ff67c0b33' in vhost '/'
2016-07-05 19:29:59.813 111142 TRACE oslo.messaging._drivers.impl_rabbit 
2016-07-05 19:29:59.826 111142 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2016-07-05 19:30:00.827 111142 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 192.168.176.131:5672
2016-07-05 19:30:00.854 111142 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 192.168.176.131:5672
2016-07-05 19:30:00.868 111142 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to publish message to topic 'reply_11a932d102d048c2ab3fd74ff67c0b33': Exchange.declare: (404) NOT_FOUND - no exchange 'reply_11a932d102d048c2ab3fd74ff67c0b33' in vhost '/'

**Comment by kangyangyang520** [comment]
你好，我用openshit安装配置好了opanstack，但在使用glance服务时，出现此类错误，
smile@smile-HP:~$ glance image-list
global name '_' is not defined
使用其他glance命令，都是提示
global name '_' is not defined
这个问题出在哪里？谢谢您的帮助。

**Comment by windworst** [comment]
我是新手, 很多问题我也不会啊
